# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockedApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_to_api', models.CharField(max_length=200)),
                ('mocked_return_value', jsonfield.fields.JSONField()),
            ],
        ),
    ]
