# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockedapi',
            name='http_method',
            field=models.CharField(choices=[(1, 'GET'), (2, 'POST'), (4, 'PUT'), (4, 'HEAD')], default=1, max_length=6),
        ),
    ]
