# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimock', '0002_mockedapi_http_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockedapi',
            name='http_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('HEAD', 'HEAD')], default='GET', max_length=6),
        ),
    ]
