# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apimock', '0003_auto_20161022_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockedApiResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mocked_return_value', jsonfield.fields.JSONField(default={b'message': b'This is storing the volatile data for api calls'})),
                ('exact_url', models.CharField(max_length=200)),
                ('callback_success', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='mockedapi',
            name='http_method',
            field=models.CharField(choices=[(b'GET', b'GET'), (b'POST', b'POST'), (b'PUT', b'PUT'), (b'HEAD', b'HEAD'), (b'PATCH', b'PATCH'), (b'DELETE', b'DELETE')], default=b'GET', max_length=6),
        ),
        migrations.AlterField(
            model_name='mockedapi',
            name='mocked_return_value',
            field=jsonfield.fields.JSONField(default={b'message': b'Please enter proper json return Value For this Api'}),
        ),
        migrations.AddField(
            model_name='mockedapiresult',
            name='original_api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimock.MockedApi'),
        ),
    ]
