# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimock', '0004_auto_20161023_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockedapi',
            name='Error_403',
            field=models.CharField(default=b'wrong used Data', max_length=200),
        ),
    ]
