# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apimock', '0005_mockedapi_error_403'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockedAPiValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_url', models.CharField(max_length=200)),
                ('mocked_return_value', jsonfield.fields.JSONField(default=b'{}')),
            ],
        ),
        migrations.AlterField(
            model_name='mockedapi',
            name='mocked_return_value',
            field=jsonfield.fields.JSONField(default=b'{"message": "Please enter json as mocked value. please change that setting"}'),
        ),
        migrations.AddField(
            model_name='mockedapivalue',
            name='original_api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimock.MockedApi'),
        ),
    ]
