# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimock', '0009_auto_20161024_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockedapi',
            name='behavior_after_post',
            field=models.CharField(default=b'', max_length=1000),
        ),
    ]
