# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimock', '0011_auto_20161024_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockedapi',
            name='behavior_after_post',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
