# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimock', '0012_auto_20161024_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mockedapi',
            old_name='Error_403',
            new_name='error_403',
        ),
        migrations.AddField(
            model_name='mockedapi',
            name='error_400',
            field=models.CharField(default=b'BAD request for this api', max_length=200),
        ),
    ]
